name: Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Set password for runneradmin
      run: |
        $SecurePassword = ConvertTo-SecureString -String $env:SSH_PASSWORD -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $SecurePassword
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Enable RDP server
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Enable SSH server
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
        Set-Service -Name sshd -StartupType 'Automatic'
        type C:\ProgramData\ssh\sshd_config
        (Get-Content C:\ProgramData\ssh\sshd_config) | ForEach-Object {$_ -replace '#PasswordAuthentication yes', 'PasswordAuthentication yes' -replace '#PubkeyAuthentication yes', 'PubkeyAuthentication yes'} | Set-Content C:\ProgramData\ssh\sshd_config
        Restart-Service sshd

    - name: Install scoop (Windows)
      uses: MinoruSekine/setup-scoop@main
      with:
        install_scoop: 'true'
        add_extras_bucket: 'true'
        scoop_update: 'true'
        update_path: 'true'

    - name: Install Tailscale via Scoop
      run: |
        scoop install tailscale

    - name: Start Tailscale
      run: |
        tailscale up

    - name: Print Tailscale IP
      run: |
        tailscale ip

    - name: Wait for 6h # A single step is limited to 6h, you can adjust the time as needed
      run: |
        echo "Now, you can connect to the GitHub Actions VM via 'ssh runneradmin@[tailscale-ip], or use RDP'"
        Start-Sleep -Seconds 21600
